logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  rabbitmq:
    host: 43.136.131.133 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: test
    password: lhj020826..
    virtual-host: /banyan
    publisher-returns: true
    publisher-confirm-type: correlated
